### ISSUE TITLE
Dot rule

### ISSUE THREAD

**Issue by icecolbeveridge** [c0stya/brzozowski#2]
Hi, 

This is really interesting, and very nicely done -- there's just one thing I don't quite follow.

In the definitions, the dot rule is given as $\partial_a (r \cdot s) = \partial_a r \mid \nu(r) \cdot \partial_a s$

In the derivation, you say: $\partial_c\left[(c \mid b)\cdot a \cdot t\right] = \partial_c \left[c \mid b\right]\cdot a \cdot t \mid \nu(c \mid b) \cdot \partial_c [a \cdot t]  \text{ by } \cdot \text{-rule}$. I don't see where the $\cdot a \cdot t$ after the first square brackets comes from.

I could very easily have misunderstood, but I'm reading $r$ as $( c \mid b)$ and $s$ as $a \cdot t$ -- so (assuming the derivation is correct) it looks like the rule ought to be $\partial_a (r \cdot s) = \partial_a r \cdot s \mid \nu(r) \cdot \partial_a s$.

Again, really enjoyable piece -- I just want to make sure I'm understanding it correctly!

**Comment by c0stya** [comment]
Hi Colin,

the derivation looks correct but I made an error in the dot rule. It should be:

∂a (r · s) = ∂a r **· s** | ν(r) · ∂a s 

I missed the 'dot s' part. Otherwise it makes no sense indeed. Thank you for pointing this out!

I'm glad you enjoyed the sketch. Will polish the code and add the automaton construction code soon.
